### PR TITLE
Minified built-in JSON maps

### PR DESCRIPTION
**Pull request by fabiospampinato**
@fb55 Here we go!

- It's a slightly more convoluted PR than I expected, because the idiot TS compiler reformatted the outputted JSON files.
- The minification brought slightly better results than I expected, partially because there where  some more files that could have used some minification.
- I used this thing for minifying files: https://codebeautify.org/jsonminifier
- I checked for equality of the new maps with the previous maps manually with this bit of code, not included in the PR because it's not really useful to run again and keeping the previous maps in the codebase seemed ugly to me:

```js
const assert = require ( 'assert' );

assert.deepStrictEqual ( require ( './maps/decode.json' ), require ( './maps.bak/decode.json' ) );
assert.deepStrictEqual ( require ( './maps/entities.json' ), require ( './maps.bak/entities.json' ) );
assert.deepStrictEqual ( require ( './maps/legacy.json' ), require ( './maps.bak/legacy.json' ) );
assert.deepStrictEqual ( require ( './maps/xml.json' ), require ( './maps.bak/xml.json' ) );
```

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Tests are passing but the linter is complaining, since it was complaining already before I made any changes, and since I'm not sure how to fix it, I left it as it was.

**Comment by fb55** [comment]
Thanks for opening this! I am a little bit confused by the inclusion of `copyfiles`. Why not do a `cp -r src/maps lib/`?

**Comment by fabiospampinato** [comment]
I wasn't sure about whether you cared about making that command work across platforms or not, but I'm reading now in `copyfiles`'s readme: "Note: on windows globs must be double quoted" so maybe I didn't use it correctly 🤔 I guess we can just use `cp`

**Comment by fabiospampinato** [comment]
@fb55 do you want me to switch to `cp` instead or do something else?

**Comment by fb55** [comment]
Hey, sorry for the delay.

> do you want me to switch to cp instead or do something else

That would be very appreciated, yes. I'm still a bit on the fence about this change; let's ship it for now, and roll things back should this lead to any unforeseen breakages.

**Comment by fb55** [comment]
Awesome, thanks a lot @fabiospampinato!

**Comment by fabiospampinato** [comment]
Thank you! 👍 

I can only see potential issues if somebody is reading the raw maps as strings directly and maybe checking for unicode escape sequences in them or something, other than that the parsed JSON files didn't really change, and it would appear that Node is parsing them them same way under every platform, so probably nobody will even notice this little change.

**Comment by fb55** [comment]
Released this as version `2.1.0`.

I am a bit worried about tools like Snowpack, that can directly include files from a module in the browser. Browsers are not always using UTF-8, so some issues could arise here. Let's see if this ever actually happens in the wild.

**Comment by fb55** [comment]
Interesting, looks like the new release actually slightly increased the bundle size: https://bundlephobia.com/result?p=entities@2.1.0

**Comment by fabiospampinato** [comment]
I was looking at that too 🤔 200 extra bytes, or 101 if the numbers got rounded up in a very unlucky way, seems impossible to me. Without seeing exactly those outputted bundles I'm not sure what's going on there.

Regarding the disappointing reported gzipped size change, none, apparently webpack already performs this optimization at build time, so it seems like this optimization is actually going to be 100% useless to me in practice, I'm guessing whatever bundler bundlephobia is using is doing the same. I should have checked this before submitting the suggestion 🤦 

I'm not sure if there are any major bundlers that would benefit from this optimization 🤔 

The NPM tarball for v2.1.0 is 161 bytes lighter than the one for v2.0.3 though, I guess we caused 100 less grams of co2 to be put in the air because of this module during next year, which is an improvement probably counterbalanced by this comment right here 😅

So yeah, sorry I didn't think that webpack could be performing this optimization too.

**Pull request merged**
