### PR TITLE
chore: improve tree shaking with pure annotations

### PR DESCRIPTION
**Pull request by Gravitonic**
Not sure if this is desired, but by adding some more `/* #__PURE__ */` function annotations, I was able to reduce bundle sizes, particularly for use cases only involving XML, since it enables bundlers to tree-shake out the HTML decoding trie. I've tested the tree-shaking behavior with [esbuild](https://github.com/evanw/esbuild) and [Rollup](https://github.com/rollup/rollup) and put the results into a gist [here](https://gist.github.com/Gravitonic/a1822579f2d0c66a97f031638b674c86). I've disabled minification for readability, so the file sizes are a bit larger, but I think the relative reductions should be comparable; in this simple case it's ~78% for Rollup and ~82% for esbuild but of course those figures would vary depending on usage.

### CODE REVIEW

**Comment by fb55** [comment]
Hi @Gravitonic, super interesting findings, thanks for this PR! I was under the impression that `sideEffects: false` in the package.json has the same effect – would you happen to know why that isn't the case?

**Comment by Gravitonic** [comment]
Honestly I'm not completely sure, but here's what I could figure out from my experiments and from what I could find in bundler documentation.

It seems like `sideEffects` applies at the file level, rather than at the level of particular exports; the bundler only skips a file's imports if none of its exports are used. For instance from the [esbuild documentation](https://esbuild.github.io/api/#ignore-annotations):

> The sideEffects field in package.json can be used to tell esbuild which files in your package can be removed if all imports from that file end up being unused.

or the [Webpack documentation](https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects):

> [The sideEffects field is] similar to `/*#__PURE__*/` but on a module level instead of a statement level. It says (`"sideEffects"` property): "If no direct export from a module flagged with no-sideEffects is used, the bundler can skip evaluating the module for side effects.".

That seems to makes sense with esbuild's metadata; here's why esbuild reports why it currently bundles `decode-data-html.js` even if only `decodeXML` is imported:

1. The input file imports from `entities` (resolved to `dist/esm/index.js`)
2. `dist/esm/index.js` imports from `./decode.js` (resolved to `dist/esm/decode.js`)
3. `dist/esm/decode.js` imports from `./generated/decode-data-html.js` (resolved to `dist/esm/generated/decode-data-html.js`)
4. So `dist/esm/generated/decode-data-html.js` is included in the bundle.

Even though the *statement* with the HTML decoding data is not used, the *file* is technically imported, and `sideEffects` only covers cases where none of a file's exports are used. So to mark the statement as having no side effects, I think that's where the `/* #__PURE__ */` annotations come in?

**Comment by fb55** [comment]
That makes sense, yes. Prettier is currently unhappy (likely the removed trailing comma in the type annotation), but otherwise I'm happy to merge this

**Comment by fb55** [comment]
Thanks for this awesome PR @Gravitonic!

**Comment by Gravitonic** [comment]
Ah, sorry I got busy during the week — thanks!

**Pull request merged**
