### PR TITLE
avoid require json fix #25

### LINKED ISSUE #25: avoid json file require for client side usage
There are some ways to use node modules on client side now, but requiring json file may not be supported that well compared to js file. For example, webpack requires an extra [json-loader](https://github.com/webpack/json-loader) plugin for that. I guess it maybe better to convert requiring json to exporting an object from js file.

### PR DESCRIPTION
**Pull request by wangzuo**

### CODE REVIEW

**Comment by fb55** [comment]
The current behavior is supported by node & browserify, please file bugs for the other projects.

**Comment by gaearon** [comment]
>please file bugs for the other projects.

Is there any chance you might change your mind?

Webpack, which is a heavily popular bundler, doesn’t support JSON out of the box. This means no library that wants to be usable from Webpack can depend on `entities`, and this constraint spreads (e.g. Webpack users can’t rely on `ansi-to-html` because it depends on `entities` which is how I got here).

It would be nice if this package was usable on Webpack too since it requires such a trivial change to non-public API. While we one argue it’s not a beautiful solution, it is a very practical one that would make some people’s lifes easier, and would not impact this project negatively.

Thank you for considering this!

**Comment by mik01aj** [comment]
The same it true for `markdown-it`, used by `react-styleguidist`. Could you reconsider merging this?

**Comment by fb55** [comment]
@mik01aj Please discuss that with the Webpack developers (or add the [single line of configuration](https://github.com/webpack/webpack/blob/17a68e7a358c03617dd0ecbd09167d5b7369641f/examples/loader/webpack.config.js#L4) to your Webpack config).

**Comment by gaearon** [comment]
@fb55 

As I said above, the problem is that if *a library* depends on entities (vast majority of cases), it can’t tell its consumers to add lines to Webpack config. Normally libraries just don’t ask you to do that, it’s fragile, not obvious, and inconvenient.

**Comment by gaearon** [comment]
Also I realize that rather than complain about this here, I should have forked this project and sent a PR to its dependents. I’m sorry for wasting your time. Unsubscribing 😉 .

**Pull request closed without merging**
