### PR TITLE
fix backward compatibility with old browsers

### PR DESCRIPTION
**Pull request by melnikaite**
#200 
#209

### CODE REVIEW

**Comment by syabro** [comment]
@melnikaite why new dependency and not just `new RegExp`?

**Comment by melnikaite** [comment]
The reason is described in the title

Unicode modifier is not supported in old browsers and node.js versions

`entities` is used as dependency of many other dependencies, so usually it's not listed in package.json

Updating `entities` to 2.0.1 broke a lot of builds

This PR solves the issue for all failed builds without any workarounds

**Comment by syabro** [comment]
I don't see any issue about "please support unicode". For 3m installs.
Why fix that is not broken by adding redundant dependency?

**Comment by melnikaite** [comment]
Main discussion is in the issue #200 
Also have a look at issue #209

**Comment by syabro** [comment]
I've seen them. By "what's broken" I mean - nobody cares about added `u` flag. So it's better remove the flag itself rather than add external dependency and 16 petabytes of traffic per week just for developers/builds.
https://www.npmjs.com/package/entities

image

**Comment by melnikaite** [comment]
Removing `u` breaks tests

**Comment by bkothe** [comment]
> @melnikaite why new dependency and not just `new RegExp`?
> 
> image
> 
> You're adding 1mb dependency to a project that doesn't have any dependency but's being used 3m times.

This was my first reaction when I saw the PR too.  I like the idea @scottaj had in #200, roll back the changes completely and create a 2.0.3 release without them, so basically 2.0.3 would be the same release as 2.0.0. Then create a 3.0.0 release that includes the changes from 2.0.1 and 2.0.2.  Those who care about the `u` flag can set a dependency ^3.0.0.  I feel that idea follows npm's versioning suggestion.

image

**Comment by Xiaochi-Li** [comment]
Can we please merge this?

**Comment by fb55** [comment]
Opted for #212 instead of this, but thanks a lot for opening it!

**Pull request closed without merging**
